- api/get-started/extension-anatomy.md
> extension-anatomy.md 번역

- README.md
- api/get-started/wrapping-up.md
- api/working-with-extensions/testing-extension.md
#8 #7 의 PR입니다.
제가 VSCode 익스텐션 Api에 대해서 잘 아는게 아니라서 오역이 많을 수도 있습니다.
예를 들어 Wrapping up의 `익스텐션 기능` 같은 경우 기여 포인트에 대해서 뭔지 몰라서 대충 의역했습니다. 추후에 확인을 해야 할 것 같습니다.
그 외에도, `vscode로부터 마이그레이션하기`의 설명이라던가 `디버깅 도중 다른 익스텐션 비활성화`의 예제 소스코드 설명 또한 원어가 애매하게 써져있어서 의역을 많이 추가했습니다. 제가 실제로 해본게 아니라서 오역이 있을거 같으니 추후에 무수한 수정의 요청 부탁드립니다
> Get Started / Wrapping up, Working with Extensions / Testing Extension 번역완료

- README.md
- api/extension-capabilities/common-capabilities.md
VS code를 안 써서 어느 부분이 Term이고 어느 부분이 단어인지 구분이 애매하네요.
리드미도 번역 완료된 부분 표기 했습니다.
> Extension Capabilities / Common Capabilities 번역완료

- README.md
- api/extension-capabilities/theming.md
- api/get-started/wrapping-up.md
- api/get-started/your-first-extension.md
- api/working-with-extensions/testing-extension.md
`Testing Extension`, `Wrapping up` 문서에서 제가 주석을 제대로 안달아서 영어가 그대로 보였어서 그 부분또한 수정했습니다.
> Extension Capabilities / Theming 번역완료

- README.md
- api/extension-capabilities/extending-workbench.md
나중에 번역 검수는 VS Code 실 사용자한테 받아야 할 듯
> Extension Capabilities / Extending Workbench 번역완료

- README.md
- api/extension-guides/virtual-documents.md
scheme 그대로 사용
46 검수 필요
172 이미지 깨짐 
178 검수 필요
> Extension Guides / Virtual Documents 번역 완료 

- README.md
> Extension Guides / Source Control 삭제

- README.md
- api/extension-guides/custom-data-extension.md
- api/extension-guides/debugger-extension.md
- api/extension-guides/markdown-extension.md
이미지 깨짐 (24, 67, 94, 186, 255, 272, 502)
> Extension Guides 번역 완료

- README.md
- api/language-extensions/overview.md
이미지 깨짐 (97, 119)
내용 빠진것 같음 (125~ 부터)
> Language Extensions / Overview 번역 완료

- README.md
- api/language-extensions/syntax-highlight-guide.md
이미지 깨짐 (66, 236, 252, 263, 278, 294, 330)
> Language Extensions / Syntax Highlight Guide 번역 완료

- README.md
- api/language-extensions/programmatic-language-features.md
이미지 깨짐 ( 121, 202, 277,  354, 429, 504, 583, 656, 731, 807, 882, 964, 1042, 1113, 1194, 1272 )
> Language Extensions / Programmatic Language Features 번역 완료 

- README.md
- api/language-extensions/language-server-extension-guide.md
이미지 깨짐 (65, 120, 680, 692, 701, 716, 723, 831, 910)
> Language Extensions / Language Server Extension Guide 번역 완료

- README.md
- api/advanced-topics/remote-extensions.md
- api/advanced-topics/using-proposed-api.md
API 이름 오타난거 수정함 `vscoode.env.asExternalUri` (668 , 671)
이미지 깨짐 (51, 924, 946)
> Advanced Topics 번역 완료

- .github/ISSUE_TEMPLATE/suggest_translate.md
> 번역 제안 이슈 템플릿 추가

- README.md
- api/advanced-topics/remote-extensions.md
- api/advanced-topics/using-proposed-api.md
- api/extension-guides/color-theme.md
- api/extension-guides/debugger-extension.md
- api/get-started/wrapping-up.md
- api/working-with-extensions/bundling-extension.md
- api/working-with-extensions/continuous-integration.md
- api/working-with-extensions/publishing-extension.md
- index.md
Issue #57 
publish를 모두 게시/게시하다로 바꿨습니다.
> Docs: Change publish

- api/advanced-topics/using-proposed-api.md
- api/working-with-extensions/continuous-integration.md
Issue #54 
branch를 브랜치로 수정했습니다.
> Change branch to 브랜치

- api/get-started/your-first-extension.md
되는지 확인 이후에, 안되면 video 파일 올려서 다시 수정.
> video 링크 수정

- _sass/custom/custom.scss
> Docs: Change width img and video tag

- README.md
- api/references/contribution-points.md
이미지 깨짐 (73, 88, 225, 239, 426, 442, 539, 599, 715, 929, 956, 1050, 1092)
> References  / Contribution Points 번역 완료

- api/references/document-selector.md
- api/references/icons-in-labels.md
> Icons In Labels, Document Selector 올립니다.

- README.md
- api/references/commands.md
`vscode.executeCodeLensProvider` 부분 내용 잘린 것 같음 (221)
> References / Commands 번역 완료

- README.md
- api/references/theme-color.md
이미지 깨짐 140, 169, 191, 428, 435, 442, 448, 454, 541, 563, 582, 605, 619, 631, 645, 654, 709, 729, 944, 987, 1155, 1162
초벌 번역 전부 끝. 아디오스
> References / Theme Color 번역 완료
